version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Title
          command: |
            echo "You can even have multiline commands."
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: 
          command: |
            if [ ! -d "~/cache/" ]; then
              mkdir ~/cache/
            fi
      - run:
          command: echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths:
            - ~/cache