version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Title
          command: |
            echo "You can even have multiline commands."
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: 
          command: mkdir ~/cache/
          when: always # ignore, even if ~/cache exists
      - run: echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths:
            - ~/cache